name: biometrics
channels:
  - apple
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - opencv
  - sqlite
  - jupyter
  - ipykernel
  - pip
  - pip:
    - kagglehub
    - "protobuf>=4.23,<5"
    # ---------- Platform-specific TensorFlow ----------
    # On macOS Apple Silicon:
    - tensorflow-macos; sys_platform == 'darwin'
    - tensorflow-metal; sys_platform == 'darwin'
    # On Windows/Linux (NVIDIA GPU):
    - tensorflow[and-cuda]; sys_platform != 'darwin'
